// `neosmith feedback [bug|idea] [--message "..."]` — file a GitHub issue.
//
// Opens the user's default browser on the right issue template (Bug for "bug",
// Enhancement for "idea") in Neosmith-ai/neosmith-connect, with a prefilled
// body that includes:
//   - a user-supplied --message (optional)
//   - a marketing-formatted "What happened / What should happen" scaffold that
//     matches the template's exact field names so reviewers don't have to
//     reparse it
//   - an auto-collected Environment block: node version, OS, CLI version,
//     router URL host (never the key)
//
// Design:
//   - Never touches the stored key. Environment data is the URL host only,
//     not the full URL with query parameters.
//   - Body is built locally and encoded into the GitHub deep-link as
//     body=<url-encoded markdown>. No network call is required unless the
//     browser launch succeeds.
//   - On headless servers (no TTY / no browser launcher), the command prints
//     the full URL and shows the prefilled body so the user can copy-paste.
//
// Supported flags:
//   -t, --type <bug|idea>          Override the default type.
//   -m, --message <text>           User's description (markdown allowed).
//       --no-open                  Print the URL and body, don't launch a browser.
//       --type / --message / --no-open can also be set via NEOSMITH env vars
//       so a test harness / CI can drive the command deterministically.

"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync } = require("child_process");

const ui = require("../ui");
const io = require("../io");
const harness = require("../harness");

const REPO = "Neosmith-ai/neosmith-connect";
const REPO_URL = `https://github.com/${REPO}`;

// GitHub's URL-encoded body has a 8192-char limit on issues; trim safely.
const MAX_BODY_CHARS = 8000;

function readPkgVersion() {
  try {
    return require("../../package.json").version;
  } catch {
    return "(unknown)";
  }
}

function envContext() {
  // Strip query strings and any path segments past the first one; we only
  // want the host so we don't leak headers/key material by accident.
  const router = harness.ROUTER_URL || "(default)";
  let host = "(default)";
  try {
    host = new URL(router).host;
  } catch { /* leave default */ }
  return {
    "CLI version": `@neosmithai/cli v${readPkgVersion()}`,
    "Node":         process.version,
    "OS":           `${os.platform()} ${os.release()} (${os.arch()})`,
    "Router":       host,
  };
}

function bodyFor({ type, message }) {
  const ctx = envContext();
  const envBlock = Object.entries(ctx)
    .map(([k, v]) => `- **${k}:** ${v}`)
    .join("\n");

  if (type === "bug") {
    return [
      "## What happened?",
      message || "<!-- Describe the bug — what you saw vs. what you expected -->",
      "",
      "## Steps to reproduce",
      "```",
      "1. Run `neosmith ___`",
      "2. <do the thing>",
      "3. Observe <broken behavior>",
      "```",
      "",
      "## Expected",
      "<!-- What should have happened instead? -->",
      "",
      "## Environment",
      envBlock,
      "",
      "> _Auto-generated by `neosmith feedback`. Edit before submitting._",
    ].join("\n");
  }
  if (type === "idea") {
    return [
      "## What should change and why?",
      message || "<!-- Describe the improvement you'd like to see. -->",
      "",
      "## Motivation",
      "<!-- What problem does it solve for you? -->",
      "",
      "## Acceptance criteria",
      "<!-- What does \"done\" look like? -->",
      "",
      "## Environment",
      envBlock,
      "",
      "> _Auto-generated by `neosmith feedback`. Edit before submitting._",
    ].join("\n");
  }
  throw new Error(`unsupported feedback type: ${type}`);
}

function buildUrl({ type, message }) {
  const template = type === "bug" ? "bug.md" : "enhancement.md";
  const title = type === "bug" ? "[Bug] " : "[Enhancement] ";
  const body = bodyFor({ type, message });
  // Use array form so encodeURIComponent's "+" vs "%20" choice is consistent
  // (encodeURIComponent produces the right shape; + is reserved for spaces too).
  const params = new URLSearchParams();
  params.set("template", template);
  params.set("title", title);
  if (body.length > MAX_BODY_CHARS) {
    const trimmed = body.slice(0, MAX_BODY_CHARS)
      + "\n\n<!-- (body truncated by `neosmith feedback`) -->";
    params.set("body", trimmed);
  } else {
    params.set("body", body);
  }
  return `${REPO_URL}/issues/new?${params.toString()}`;
}

function parseFlags(args) {
  const out = { type: null, message: null, noOpen: false };
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === "--no-open" || a === "--print-only") { out.noOpen = true; continue; }
    if (a === "-t" || a === "--type") { out.type = args[++i] || ""; continue; }
    if (a.startsWith("--type=")) { out.type = a.slice("--type=".length); continue; }
    if (a === "-m" || a === "--message") { out.message = args[++i] || ""; continue; }
    if (a.startsWith("--message=")) { out.message = a.slice("--message=".length); continue; }
    if ((a === "bug" || a === "idea") && !out.type) { out.type = a; continue; }
    // Bare word that isn't a known flag: treat as a short message (so
    // `neosmith feedback bug "Tab autocomplete broken in Cursor"` works).
    out.message = (out.message ? out.message + " " : "") + a;
  }
  // Trim trailing whitespace the bare-message path may have introduced.
  if (typeof out.message === "string") out.message = out.message.trim() || null;
  return out;
}

function resolveType(raw) {
  if (raw) {
    const norm = String(raw).toLowerCase();
    if (norm === "bug" || norm === "idea") return norm;
    throw new Error(`unknown --type "${raw}" (use "bug" or "idea")`);
  }
  return "bug"; // sensible default — most feedback is a "not working" signal
}

function tryOpen(url) {
  if (process.platform === "win32") {
    return spawnSync("rundll32", ["url.dll,FileProtocolHandler", url],
      { stdio: "ignore", shell: false });
  }
  if (process.platform === "darwin") {
    return spawnSync("open", [url], { stdio: "ignore" });
  }
  // Linux / other: prefer xdg-open.
  return spawnSync("xdg-open", [url], { stdio: "ignore" });
}

async function run(args) {
  const flags = parseFlags(args);
  const type = resolveType(flags.type);
  const url = buildUrl({ type, message: flags.message });
  const body = bodyFor({ type, message: flags.message });

  ui.banner("NeoSmith · feedback");
  ui.log(`Opening ${type === "bug" ? "Bug" : "Enhancement"} template in ${REPO}`);
  ui.log(ui.c("dim", url));
  ui.log("");
  ui.log(ui.c("dim", "Auto-included in the issue body:"));
  for (const [k, v] of Object.entries(envContext())) {
    ui.log(ui.c("dim", `  ${k}: ${v}`));
  }
  if (flags.message) {
    ui.log("");
    ui.log(ui.c("dim", "Your message will appear under the template's \"What happened\" / \"What should change\" section."));
  }
  if (flags.noOpen) {
    ui.ok("--no-open: pasted URL above; body shown below for copy-paste.");
    ui.log("");
    ui.log(body);
    return { url, type, opened: false };
  }

  const r = tryOpen(url);
  const ok = r.status === 0;
  if (!ok) {
    // Common on headless: still useful to dump the URL + body so the user
    // can paste manually or push the issue from another machine.
    const reason = (r.error && r.error.message) || `exit ${r.status}`;
    ui.warn(`Could not launch the browser (${reason}). URL + prefilled body below.`);
    ui.log("");
    ui.log(url);
    ui.log("");
    ui.log(body);
    return { url, type, opened: false };
  }
  ui.ok(`Opened ${type === "bug" ? "bug" : "enhancement"} template in your default browser.`);
  ui.log(ui.c("dim", `If the browser didn't open, paste this URL manually:\n${url}`));
  return { url, type, opened: true };
}

module.exports = { run, buildUrl, bodyFor, envContext, parseFlags, resolveType };
